name: CFN TEST MongoDB Atlas CloudFormation Resources
on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        default: "us-east-1"
        required: true
jobs:
  atlas-cfn-deploy:
    name: atlas-cfn-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: pull code
      - name: test the resources
        uses: ./.github/actions/atlas-cfn-test
        with:
          ATLAS_ORG_ID_CFN: ${{ secrets.ATLAS_ORG_ID_CFN }}
          ATLAS_PUBLIC_KEY_CFN: ${{ secrets.ATLAS_PUBLIC_KEY_CFN }}
          ATLAS_PRIVATE_KEY_CFN: ${{ secrets.ATLAS_PRIVATE_KEY_CFN }}
          
