# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Find latest changes in Mongodb OpenAPI

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 9 * * 1' # At 09:00 on Monday

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: | 
        cd cfn-resources
        go mod tidy
        cd autogen
        ./compare.sh
        
        
        
        
